# -*- coding: utf-8 -*-
"""logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHGRtkhMYlEIScs89JCQypRWuCh4Ibk8
"""

!pip install kaggle

from google.colab import files
files.upload()

# Create a directory named .kaggle
!mkdir -p ~/.kaggle

# Move the kaggle.json file to that directory
!cp kaggle.json ~/.kaggle/

# Set the file's permissions to be readable only by you
!chmod 600 ~/.kaggle/kaggle.json

!kaggle competitions download -c titanic

# Step 1: Unzip the archive in your Colab/Jupyter environment
!unzip titanic.zip

# Step 2: Now read the extracted CSV file
import pandas as pd
df = pd.read_csv('train.csv')

df.head()

df.info()

df['Age'].fillna(df['Age'].median(), inplace=True)

df['Embarked'].mode()[0]

df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df.head()

df=df.drop(['PassengerId','Name','Ticket',"Cabin"],axis=1)

df.head()

df.info()

df=pd.get_dummies(df,columns=['Sex','Embarked'],drop_first=True)

df.head()

val_cnts=df["Survived"].value_counts()

val_cnts

import matplotlib.pyplot as plt
plt.hist(val_cnts,bins=30)

x=df.drop(['Survived'],axis=1)
y=df['Survived']

#x.shape
y.shape

import seaborn as sns
plt.figure(figsize=(10,8))
sns.heatmap(df.corr(),annot=True,cmap='coolwarm',fmt=".2f")

from  sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

from sklearn.metrics import accuracy_score,classification_report
accuracy=accuracy_score(y_test,y_pred)

accuracy

report=classification_report(y_test,y_pred)

print(report)

# Your single passenger's data as a list within a list (to make it 2D)
chumma_data = [[1, 30, 0, 0, 70, False, False, True]]

# The column names from your training data
feature_columns = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male', 'Embarked_Q', 'Embarked_S']

# Create the DataFrame
passenger_df = pd.DataFrame(chumma_data, columns=feature_columns)
ans=model.predict(passenger_df)

ans

if ans[0] == 1:
    print("Prediction: Survived 👍")
else:
    print("Prediction: Did not Survive 👎")

